version: '3'

services:
  ourlib:
    image: ourlib:pre-test
    container_name: ourlib-cont
    depends_on:
      - mongodb
    ports:
      - '9090:7070'
    environment:
      DNS_ADDRESS: http://localhost:9090
      DATABASE_NAME : mydb
      MONGO_URL: mongodb://root:pass@mongodb:27017
    networks:
      - backend-network
      - frontend-network
    volumes:
      - static-files:/app/templates

  mongodb:
    image: mongo:6-jammy
    container_name: mongo-container
    # ports:
    #   - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - '80:80'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static-files:/etc/nginx/html
    depends_on:
      - ourlib
    networks:
      - frontend-network

volumes:
  static-files:
  mongo-data:

networks:
  backend-network:
  frontend-network:
